dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/grails-core' }
        maven { url 'https://raw.githubusercontent.com/saki4510t/libcommon/master/repository/' }
        maven { url 'https://gitee.com/liuchaoya/libcommon/raw/master/repository/' }
        maven { url "https://repo.eclipse.org/content/repositories/paho-snapshots/" }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://www.jitpack.io' }
    }
}

rootProject.name = "ANetKit"
include ':app'
include ':coil1'
include ':coil2'
include ':coil2-compose'
include ':coil2:test'
include ':connection'
include ':connection:test'
include ':fastimagesize'
include ':fastimagesize-ext'
include ':fastimagesize-ext:exam'
include ':file-download'
include ':file-download:test'
include ':file-okdownload'
include ':file-okdownload:test'
include ':glide'
include ':glide:test'
include ':glide-blur'
include ':glide-compose'
include ':glide-ext'
include ':mqtt'
include ':mqtt:test'
include ':netk'
include ':observer'
include ':observer:test'
include ':retrofit2'
include ':retrofit2:test'
include ':netty'
include ':okhttp3'
include ':netty:test'
include ':okhttp3-cache'
include ':okhttp3-interceptor'
include ':os-basic'
include ':os-cos'
include ':os-oss'
include ':os:test'
include ':picasso'
include ':retrofit2-cache'
include ':retrofit2-cache:test'
include ':retrofit2-converter_kotlinx_serialization'
include ':retrofit2-adapter_kotlinx_coroutines'

